import type { Metadata } from "next";
import "@/styles/globals.css"

import { Open_Sans as FontSans } from "next/font/google";
import { cn } from "@/lib/utils"

import { Providers } from '@/redux/provider';
import { Suspense } from "react";
import { Loading } from "@/components/loading";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans", })

export const metadata: Metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
          >
          <Suspense fallback={<Loading />}>
            <Providers>
              {children}
            </Providers>
          </Suspense>
        </body>
      </html>
  );
}
